# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lEGeq9--vkYn9_VFjkFbRM6u_UDNljTa
"""

import pandas as pd

# Q.1
df = {"ProductID":[101,102,103,104,105],
     "Product":["Widget","Gadget","Doodad","Thingamajig","Whatchamacallit"],
     "Price": [10.99,24.95,5.99,15.50,8.75],
     "UnitsSold": [120,85,230,150,200]}
df1 = pd.DataFrame(data=df)

# Q.2
print(df1)

# Q.3
df1["Total_price"] = df1["Price"] * df1["UnitsSold"]
df1.head()

#Q.4
avg_price = df1['Price'].mean()
print(avg_price)

#Q.5
df1[df1['Price'] > 15]

#Q.6
df1.sort_values(by=['Total_price'],ascending=False)

#Q.7
df1[df1['Total_price'] == df1['Total_price'].max()]

#Q.8
(df1["Total_price"] /df1["Total_price"].sum() ) *100

