# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dooJOGGM_xIe16bzfqix6FmyyYIIHgtn
"""

!kaggle datasets download -d sonalisingh1411/mallcustomersdataset

!unzip -q /content/mallcustomersdataset.zip -d /content

import pandas as pd
df = pd.read_csv('/content/Mall_Customers.csv')
df.head(3)

df.drop(['CustomerID','Genre'], axis=1, inplace=True)
df.head(3)

df.isnull().sum()

df.duplicated().sum()

import matplotlib.pyplot as plt
import seaborn as sns
from scipy.cluster.hierarchy import dendrogram, linkage

# Calculate the linkage matrix
linked = linkage(df, 'ward')

# Plot the dendrogram
dendrogram(linked)
plt.title('Dendrogram')
plt.xlabel('Customers')
plt.ylabel('Distance')
plt.show()

dendrogram(linked)
plt.axhline(y=300,color='r')
plt.title('Dendrogram')
plt.xlabel('Customers')
plt.ylabel('Distance')
plt.show()

from sklearn.cluster import AgglomerativeClustering
hc = AgglomerativeClustering(n_clusters=3, metric='euclidean', linkage='ward')
hc.fit_predict(df)

plt.scatter(df.iloc[:,1],df.iloc[:,2],c=hc.labels_)
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')
plt.show()

from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)

dbscan = DBSCAN(eps=0.5,min_samples=5)
dbscan.fit_predict(df_scaled)

plt.scatter(df.iloc[:,1],df.iloc[:,2],c=dbscan.labels_)
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.title('DBSCAN Clustering')
plt.colorbar(label='Cluster Label')
plt.show()

